import { readImageBySlug } from "./images";
import { readSetBySlug } from "./sets";

export const allWorks = [
  {
    date: "2022-06-22 12:00:00.000Z",
    height: 32,
    imageSlug: "bumblebee",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "bestiaire",
    slug: "bumblebee",
    title: "Bumblebee",
    width: 24,
  },
  {
    date: "2023-01-23 12:00:00.000Z",
    height: 24,
    imageSlug: "je-te-vois",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "animal-totem",
    slug: "je-te-vois",
    title: "Je te vois",
    width: 32,
  },
  {
    date: "2022-05-26 12:00:00.000Z",
    height: 35,
    imageSlug: "flamingo",
    material: "canvas",
    media: ["oil"],
    setSlug: "bestiaire",
    slug: "flamingo",
    title: "Flamingo",
    width: 27,
  },
  {
    date: "2022-07-09 12:00:00.000Z",
    height: 32,
    imageSlug: "le-protecteur",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "bestiaire",
    slug: "le-protecteur",
    title: "Le protecteur",
    width: 24,
  },
  {
    date: "2022-07-30 12:00:00.000Z",
    height: 32,
    imageSlug: "beaute-i",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "ode-a-la-beaute",
    slug: "beaute-i",
    title: "Beauté I",
    width: 24,
  },
  {
    date: "2022-07-30 12:00:00.000Z",
    height: 32,
    imageSlug: "beaute-ii",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "ode-a-la-beaute",
    slug: "beaute-ii",
    title: "Beauté II",
    width: 24,
  },
  {
    date: "2022-11-11 12:00:00.000Z",
    height: 50,
    imageSlug: "chloris",
    material: "canvas",
    media: ["mixedMedia"],
    setSlug: "ode-a-la-beaute",
    slug: "chloris",
    title: "Chloris",
    width: 40,
  },
  {
    date: "2021-12-11 12:00:00.000Z",
    height: 40,
    imageSlug: "fleurir",
    material: "canvas",
    media: ["oil"],
    setSlug: "ode-a-la-beaute",
    slug: "fleurir",
    title: "Fleurir",
    width: 30,
  },
  {
    date: "2022-10-21 12:00:00.000Z",
    height: 50,
    imageSlug: "l-appel-au-repos",
    material: "canvas",
    media: ["acrylic", "oil"],
    setSlug: "ode-a-la-beaute",
    slug: "l-appel-au-repos",
    title: "L'appel au repos",
    width: 50,
  },
  {
    date: "2022-09-18 12:00:00.000Z",
    height: 50,
    imageSlug: "l-endroit-qui-m-a-vue-grandir",
    material: "canvas",
    media: ["mixedMedia"],
    setSlug: "ode-a-la-beaute",
    slug: "l-endroit-qui-m-a-vue-grandir",
    title: "L'endroit qui m'a vue grandir",
    width: 50,
  },
  {
    date: "2021-12-20 12:00:00.000Z",
    height: 27,
    imageSlug: "la-fille-a-la-fougere",
    material: "canvas",
    media: ["oil"],
    setSlug: "ode-a-la-beaute",
    slug: "la-fille-a-la-fougere",
    title: "La fille à la fougère",
    width: 19,
  },
  {
    date: "2022-08-21 12:00:00.000Z",
    height: 32,
    imageSlug: "la-reveuse",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "ode-a-la-beaute",
    slug: "la-reveuse",
    title: "La rêveuse",
    width: 24,
  },
  {
    date: "2022-11-02 12:00:00.000Z",
    height: 40,
    imageSlug: "la-volonte",
    material: "canvas",
    media: ["mixedMedia"],
    setSlug: "animal-totem",
    slug: "la-volonte",
    title: "La volonté",
    width: 60,
  },
  {
    date: "2022-09-03 12:00:00.000Z",
    height: 40,
    imageSlug: "le-bruit-de-la-nuit",
    material: "canvas",
    media: ["mixedMedia"],
    setSlug: "ode-a-la-beaute",
    slug: "le-bruit-de-la-nuit",
    title: "Le bruit de la nuit",
    width: 30,
  },
  {
    date: "2023-01-18 12:00:00.000Z",
    height: 40,
    imageSlug: "ma-vraie-nature",
    material: "canvas",
    media: ["mixedMedia"],
    setSlug: "animal-totem",
    slug: "ma-vraie-nature",
    title: "Ma vraie nature",
    width: 60,
  },
  {
    date: "2022-10-02 12:00:00.000Z",
    height: 24,
    imageSlug: "mains-i",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "la-poetique-des-mains",
    slug: "mains-i",
    title: "Mains I",
    width: 32,
  },
  {
    date: "2022-10-10 12:00:00.000Z",
    height: 32,
    imageSlug: "mains-ii",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "la-poetique-des-mains",
    slug: "mains-ii",
    title: "Mains II",
    width: 24,
  },
  {
    date: "2022-10-02 12:00:00.000Z",
    height: 32,
    imageSlug: "mains-iii",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "la-poetique-des-mains",
    slug: "mains-iii",
    title: "Mains III",
    width: 24,
  },
  {
    date: "2022-10-10 12:00:00.000Z",
    height: 22,
    imageSlug: "mains-iv",
    material: "paper",
    media: ["oil", "acrylic"],
    setSlug: "la-poetique-des-mains",
    slug: "mains-iv",
    title: "Mains IV",
    width: 14,
  },
  {
    date: "2022-10-10 12:00:00.000Z",
    height: 22,
    imageSlug: "mains-v",
    material: "paper",
    media: ["acrylic", "oil"],
    setSlug: "la-poetique-des-mains",
    slug: "mains-v",
    title: "Mains V",
    width: 14,
  },
  {
    date: "2022-10-10 12:00:00.000Z",
    height: 32,
    imageSlug: "mains-vi",
    material: "paper",
    media: ["oil"],
    setSlug: "la-poetique-des-mains",
    slug: "mains-vi",
    title: "Mains VI",
    width: 24,
  },
  {
    date: "2022-10-10 12:00:00.000Z",
    height: 32,
    imageSlug: "mains-vii",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "la-poetique-des-mains",
    slug: "mains-vii",
    title: "Mains VII",
    width: 24,
  },
  {
    date: "2022-03-20 12:00:00.000Z",
    height: 40,
    imageSlug: "peacock",
    material: "canvas",
    media: ["oil"],
    setSlug: "bestiaire",
    slug: "peacock",
    title: "Peacock",
    width: 30,
  },
  {
    date: "2022-10-15 12:00:00.000Z",
    height: 70,
    imageSlug: "perdue-dans-la-jungle",
    material: "canvas",
    media: ["oil"],
    setSlug: "animal-totem",
    slug: "perdue-dans-la-jungle",
    title: "Perdue dans la jungle",
    width: 50,
  },
  {
    date: "2022-12-20 12:00:00.000Z",
    height: 50,
    imageSlug: "renaissance",
    material: "canvas",
    media: ["mixedMedia"],
    setSlug: "ode-a-la-beaute",
    slug: "renaissance",
    title: "Renaissance",
    width: 40,
  },
  {
    date: "2022-06-06 12:00:00.000Z",
    height: 32,
    imageSlug: "ressentir-le-monde",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "ode-a-la-beaute",
    slug: "ressentir-le-monde",
    title: "Ressentir le monde",
    width: 24,
  },
  {
    date: "2022-05-26 12:00:00.000Z",
    height: 35,
    imageSlug: "serpent-vif",
    material: "canvas",
    media: ["oil"],
    setSlug: "bestiaire",
    slug: "serpent-vif",
    title: "Serpent vif",
    width: 27,
  },
  {
    date: "2022-07-15 12:00:00.000Z",
    height: 32,
    imageSlug: "toucan",
    material: "paper",
    media: ["mixedMedia"],
    setSlug: "bestiaire",
    slug: "toucan",
    title: "Toucan",
    width: 24,
  },
] as const;

export const workFrom = ({ date, height, imageSlug, material, media, setSlug, slug, title, width }: Works["Entry"]) => ({
  date: new Date(date),
  height,
  image: readImageBySlug(imageSlug),
  material,
  media,
  set: readSetBySlug(setSlug),
  slug,
  title,
  width,
});

export const readLastWorks = (count: number) =>
  [...allWorks]
    .sort((a, b) => b.date.localeCompare(a.date))
    .slice(0, count)
    .map(workFrom);

export type Works = { Entity: ReturnType<typeof workFrom>; Entry: (typeof allWorks)[number] };
