/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedMemberRouteImport } from './routes/_authenticated/_member'
import { Route as AuthenticatedAccesRefuseRouteImport } from './routes/_authenticated/acces-refuse'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ConnexionIndexRouteImport } from './routes/connexion/index'
import { Route as AuthenticatedMemberIndexRouteImport } from './routes/_authenticated/_member/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedAdminEbooksIndexRouteImport } from './routes/_authenticated/admin/ebooks/index'
import { Route as AuthenticatedAdminEmailOperationsIndexRouteImport } from './routes/_authenticated/admin/email-operations/index'
import { Route as AuthenticatedAdminPacksIndexRouteImport } from './routes/_authenticated/admin/packs/index'
import { Route as AuthenticatedAdminPacksPackIdRouteImport } from './routes/_authenticated/admin/packs/$packId'
import { Route as AuthenticatedAdminPrivacyIndexRouteImport } from './routes/_authenticated/admin/privacy/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMemberRoute = AuthenticatedMemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccesRefuseRoute =
  AuthenticatedAccesRefuseRouteImport.update({
    id: '/acces-refuse',
    path: '/acces-refuse',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ConnexionIndexRoute = ConnexionIndexRouteImport.update({
  id: '/connexion/',
  path: '/connexion/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMemberIndexRoute =
  AuthenticatedMemberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminEbooksIndexRoute =
  AuthenticatedAdminEbooksIndexRouteImport.update({
    id: '/ebooks/',
    path: '/ebooks/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailOperationsIndexRoute =
  AuthenticatedAdminEmailOperationsIndexRouteImport.update({
    id: '/email-operations/',
    path: '/email-operations/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPacksIndexRoute =
  AuthenticatedAdminPacksIndexRouteImport.update({
    id: '/packs/',
    path: '/packs/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPacksPackIdRoute =
  AuthenticatedAdminPacksPackIdRouteImport.update({
    id: '/packs/$packId',
    path: '/packs/$packId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPrivacyIndexRoute =
  AuthenticatedAdminPrivacyIndexRouteImport.update({
    id: '/privacy/',
    path: '/privacy/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedMemberIndexRoute
  '/acces-refuse': typeof AuthenticatedAccesRefuseRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/connexion/': typeof ConnexionIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/packs/$packId': typeof AuthenticatedAdminPacksPackIdRoute
  '/admin/ebooks/': typeof AuthenticatedAdminEbooksIndexRoute
  '/admin/email-operations/': typeof AuthenticatedAdminEmailOperationsIndexRoute
  '/admin/packs/': typeof AuthenticatedAdminPacksIndexRoute
  '/admin/privacy/': typeof AuthenticatedAdminPrivacyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedMemberIndexRoute
  '/acces-refuse': typeof AuthenticatedAccesRefuseRoute
  '/connexion': typeof ConnexionIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/packs/$packId': typeof AuthenticatedAdminPacksPackIdRoute
  '/admin/ebooks': typeof AuthenticatedAdminEbooksIndexRoute
  '/admin/email-operations': typeof AuthenticatedAdminEmailOperationsIndexRoute
  '/admin/packs': typeof AuthenticatedAdminPacksIndexRoute
  '/admin/privacy': typeof AuthenticatedAdminPrivacyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_member': typeof AuthenticatedMemberRouteWithChildren
  '/_authenticated/acces-refuse': typeof AuthenticatedAccesRefuseRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/connexion/': typeof ConnexionIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/_member/': typeof AuthenticatedMemberIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/packs/$packId': typeof AuthenticatedAdminPacksPackIdRoute
  '/_authenticated/admin/ebooks/': typeof AuthenticatedAdminEbooksIndexRoute
  '/_authenticated/admin/email-operations/': typeof AuthenticatedAdminEmailOperationsIndexRoute
  '/_authenticated/admin/packs/': typeof AuthenticatedAdminPacksIndexRoute
  '/_authenticated/admin/privacy/': typeof AuthenticatedAdminPrivacyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acces-refuse'
    | '/admin'
    | '/connexion/'
    | '/api/auth/$'
    | '/admin/'
    | '/admin/packs/$packId'
    | '/admin/ebooks/'
    | '/admin/email-operations/'
    | '/admin/packs/'
    | '/admin/privacy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acces-refuse'
    | '/connexion'
    | '/api/auth/$'
    | '/admin'
    | '/admin/packs/$packId'
    | '/admin/ebooks'
    | '/admin/email-operations'
    | '/admin/packs'
    | '/admin/privacy'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_member'
    | '/_authenticated/acces-refuse'
    | '/_authenticated/admin'
    | '/connexion/'
    | '/api/auth/$'
    | '/_authenticated/_member/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/packs/$packId'
    | '/_authenticated/admin/ebooks/'
    | '/_authenticated/admin/email-operations/'
    | '/_authenticated/admin/packs/'
    | '/_authenticated/admin/privacy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConnexionIndexRoute: typeof ConnexionIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_member': {
      id: '/_authenticated/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMemberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acces-refuse': {
      id: '/_authenticated/acces-refuse'
      path: '/acces-refuse'
      fullPath: '/acces-refuse'
      preLoaderRoute: typeof AuthenticatedAccesRefuseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/connexion/': {
      id: '/connexion/'
      path: '/connexion'
      fullPath: '/connexion/'
      preLoaderRoute: typeof ConnexionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_member/': {
      id: '/_authenticated/_member/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMemberIndexRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/ebooks/': {
      id: '/_authenticated/admin/ebooks/'
      path: '/ebooks'
      fullPath: '/admin/ebooks/'
      preLoaderRoute: typeof AuthenticatedAdminEbooksIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email-operations/': {
      id: '/_authenticated/admin/email-operations/'
      path: '/email-operations'
      fullPath: '/admin/email-operations/'
      preLoaderRoute: typeof AuthenticatedAdminEmailOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packs/': {
      id: '/_authenticated/admin/packs/'
      path: '/packs'
      fullPath: '/admin/packs/'
      preLoaderRoute: typeof AuthenticatedAdminPacksIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packs/$packId': {
      id: '/_authenticated/admin/packs/$packId'
      path: '/packs/$packId'
      fullPath: '/admin/packs/$packId'
      preLoaderRoute: typeof AuthenticatedAdminPacksPackIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/privacy/': {
      id: '/_authenticated/admin/privacy/'
      path: '/privacy'
      fullPath: '/admin/privacy/'
      preLoaderRoute: typeof AuthenticatedAdminPrivacyIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedMemberRouteChildren {
  AuthenticatedMemberIndexRoute: typeof AuthenticatedMemberIndexRoute
}

const AuthenticatedMemberRouteChildren: AuthenticatedMemberRouteChildren = {
  AuthenticatedMemberIndexRoute: AuthenticatedMemberIndexRoute,
}

const AuthenticatedMemberRouteWithChildren =
  AuthenticatedMemberRoute._addFileChildren(AuthenticatedMemberRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPacksPackIdRoute: typeof AuthenticatedAdminPacksPackIdRoute
  AuthenticatedAdminEbooksIndexRoute: typeof AuthenticatedAdminEbooksIndexRoute
  AuthenticatedAdminEmailOperationsIndexRoute: typeof AuthenticatedAdminEmailOperationsIndexRoute
  AuthenticatedAdminPacksIndexRoute: typeof AuthenticatedAdminPacksIndexRoute
  AuthenticatedAdminPrivacyIndexRoute: typeof AuthenticatedAdminPrivacyIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPacksPackIdRoute: AuthenticatedAdminPacksPackIdRoute,
  AuthenticatedAdminEbooksIndexRoute: AuthenticatedAdminEbooksIndexRoute,
  AuthenticatedAdminEmailOperationsIndexRoute:
    AuthenticatedAdminEmailOperationsIndexRoute,
  AuthenticatedAdminPacksIndexRoute: AuthenticatedAdminPacksIndexRoute,
  AuthenticatedAdminPrivacyIndexRoute: AuthenticatedAdminPrivacyIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedMemberRoute: typeof AuthenticatedMemberRouteWithChildren
  AuthenticatedAccesRefuseRoute: typeof AuthenticatedAccesRefuseRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMemberRoute: AuthenticatedMemberRouteWithChildren,
  AuthenticatedAccesRefuseRoute: AuthenticatedAccesRefuseRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConnexionIndexRoute: ConnexionIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
