/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AuthenticatedMemberRouteImport } from './routes/_authenticated/_member'
import { Route as AuthenticatedAccesRefuseRouteImport } from './routes/_authenticated/acces-refuse'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMemberIndexRouteImport } from './routes/_authenticated/_member/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminEbooksRouteImport } from './routes/_authenticated/admin/ebooks'
import { Route as AuthenticatedAdminEmailOperationsRouteImport } from './routes/_authenticated/admin/email-operations'
import { Route as AuthenticatedAdminPrivacyRouteImport } from './routes/_authenticated/admin/privacy'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMemberRoute = AuthenticatedMemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccesRefuseRoute =
  AuthenticatedAccesRefuseRouteImport.update({
    id: '/acces-refuse',
    path: '/acces-refuse',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemberIndexRoute =
  AuthenticatedMemberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEbooksRoute =
  AuthenticatedAdminEbooksRouteImport.update({
    id: '/ebooks',
    path: '/ebooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailOperationsRoute =
  AuthenticatedAdminEmailOperationsRouteImport.update({
    id: '/email-operations',
    path: '/email-operations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPrivacyRoute =
  AuthenticatedAdminPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedMemberIndexRoute
  '/connexion': typeof ConnexionRoute
  '/acces-refuse': typeof AuthenticatedAccesRefuseRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/admin/email-operations': typeof AuthenticatedAdminEmailOperationsRoute
  '/admin/privacy': typeof AuthenticatedAdminPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedMemberIndexRoute
  '/connexion': typeof ConnexionRoute
  '/acces-refuse': typeof AuthenticatedAccesRefuseRoute
  '/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/admin/email-operations': typeof AuthenticatedAdminEmailOperationsRoute
  '/admin/privacy': typeof AuthenticatedAdminPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/_authenticated/_member': typeof AuthenticatedMemberRouteWithChildren
  '/_authenticated/acces-refuse': typeof AuthenticatedAccesRefuseRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/_authenticated/admin/email-operations': typeof AuthenticatedAdminEmailOperationsRoute
  '/_authenticated/admin/privacy': typeof AuthenticatedAdminPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/_member/': typeof AuthenticatedMemberIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/acces-refuse'
    | '/admin'
    | '/admin/ebooks'
    | '/admin/email-operations'
    | '/admin/privacy'
    | '/api/auth/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/acces-refuse'
    | '/admin/ebooks'
    | '/admin/email-operations'
    | '/admin/privacy'
    | '/api/auth/$'
    | '/admin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/connexion'
    | '/_authenticated/_member'
    | '/_authenticated/acces-refuse'
    | '/_authenticated/admin'
    | '/_authenticated/admin/ebooks'
    | '/_authenticated/admin/email-operations'
    | '/_authenticated/admin/privacy'
    | '/api/auth/$'
    | '/_authenticated/_member/'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_member': {
      id: '/_authenticated/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMemberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acces-refuse': {
      id: '/_authenticated/acces-refuse'
      path: '/acces-refuse'
      fullPath: '/acces-refuse'
      preLoaderRoute: typeof AuthenticatedAccesRefuseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_member/': {
      id: '/_authenticated/_member/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMemberIndexRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ebooks': {
      id: '/_authenticated/admin/ebooks'
      path: '/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AuthenticatedAdminEbooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email-operations': {
      id: '/_authenticated/admin/email-operations'
      path: '/email-operations'
      fullPath: '/admin/email-operations'
      preLoaderRoute: typeof AuthenticatedAdminEmailOperationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/privacy': {
      id: '/_authenticated/admin/privacy'
      path: '/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AuthenticatedAdminPrivacyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMemberRouteChildren {
  AuthenticatedMemberIndexRoute: typeof AuthenticatedMemberIndexRoute
}

const AuthenticatedMemberRouteChildren: AuthenticatedMemberRouteChildren = {
  AuthenticatedMemberIndexRoute: AuthenticatedMemberIndexRoute,
}

const AuthenticatedMemberRouteWithChildren =
  AuthenticatedMemberRoute._addFileChildren(AuthenticatedMemberRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEbooksRoute: typeof AuthenticatedAdminEbooksRoute
  AuthenticatedAdminEmailOperationsRoute: typeof AuthenticatedAdminEmailOperationsRoute
  AuthenticatedAdminPrivacyRoute: typeof AuthenticatedAdminPrivacyRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEbooksRoute: AuthenticatedAdminEbooksRoute,
  AuthenticatedAdminEmailOperationsRoute:
    AuthenticatedAdminEmailOperationsRoute,
  AuthenticatedAdminPrivacyRoute: AuthenticatedAdminPrivacyRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedMemberRoute: typeof AuthenticatedMemberRouteWithChildren
  AuthenticatedAccesRefuseRoute: typeof AuthenticatedAccesRefuseRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMemberRoute: AuthenticatedMemberRouteWithChildren,
  AuthenticatedAccesRefuseRoute: AuthenticatedAccesRefuseRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
