import { blurhashToCssGradientString } from "@unpic/placeholder";

export const allImages = [
  {
    alt: "Contact",
    blurhash: "UBE.*3-=Ac000K4:IU-o56RP$eM_~W-;gNb_",
    height: 3888,
    slug: "contact",
    src: "https://ik.imagekit.io/elianacorre/contact.jpeg",
    width: 4809,
  },
  {
    alt: "Accueil",
    blurhash: "UBE.*3-=Ac000K4:IU-o56RP$eM_~W-;gNb_",
    height: 3840,
    slug: "accueil",
    src: "https://ik.imagekit.io/elianacorre/accueil.jpeg",
    width: 2560,
  },
  {
    alt: "Mes œuvres",
    blurhash: "UBE.*3-=Ac000K4:IU-o56RP$eM_~W-;gNb_",
    height: 3840,
    slug: "mes-oeuvres",
    src: "https://ik.imagekit.io/elianacorre/mes-oeuvres.JPG",
    width: 2560,
  },
  {
    alt: "Découvrez mon parcours",
    blurhash: "UBE.*3-=Ac000K4:IU-o56RP$eM_~W-;gNb_",
    height: 3888,
    slug: "decouvrez-mon-parcours",
    src: "https://ik.imagekit.io/elianacorre/decouvrez-mon-parcours.jpg",
    width: 5184,
  },
  {
    alt: "Mes inspirations et mes techniques",
    blurhash: "UBE.*3-=Ac000K4:IU-o56RP$eM_~W-;gNb_",
    height: 3808,
    slug: "mes-inspirations-et-mes-techniques",
    src: "https://ik.imagekit.io/elianacorre/mes-inspirations-et-mes-techniques.jpeg",
    width: 3888,
  },
  {
    alt: "Beauté I",
    blurhash: "UQIXW[.9}@=J-SxZIAMx?Gt7V]kp-QRk$%Rk",
    height: 2567,
    slug: "beaute-i",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/beaute-i.jpeg",
    width: 1896,
  },
  {
    alt: "Beauté II",
    blurhash: "UAGk]k00%NX1|GKhEN=rTvPS;MTIsFY0XN+$",
    height: 2495,
    slug: "beaute-ii",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/beaute-ii.jpeg",
    width: 1907,
  },
  {
    alt: "Bumblebee",
    blurhash: "U9B#Oe%rC:-AGP9IH%t73KxGr3bbr~RRIoWT",
    height: 2612,
    slug: "bumblebee",
    src: "https://ik.imagekit.io/elianacorre/bestiaire/bumblebee.png",
    width: 1916,
  },
  {
    alt: "Chloris",
    blurhash: "UBKwCa000RY800.2$nyX7MA0?vI^D#-Vrov~",
    height: 4136,
    slug: "chloris",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/chloris.jpeg",
    width: 3290,
  },
  {
    alt: "Flamingo",
    blurhash: "UBD9SVTC0eMwyFtSRPRk00nO}]og9aM{$*o}",
    height: 4087,
    slug: "flamingo",
    src: "https://ik.imagekit.io/elianacorre/bestiaire/flamingo.jpeg",
    width: 3084,
  },
  {
    alt: "Fleurir",
    blurhash: "UCBNA_=q1l5A_2?ZM|I[L4ny=_%1KkRi-o$e",
    height: 2600,
    slug: "fleurir",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/fleurir.png",
    width: 1940,
  },
  {
    alt: "Je te vois",
    blurhash: "U5F$Li0F00VQ-tP65ro#+hk=5Z*_6X^+xZof",
    height: 3062,
    slug: "je-te-vois",
    src: "https://ik.imagekit.io/elianacorre/animal-totem/je-te-vois.jpeg",
    width: 4113,
  },
  {
    alt: "L'appel au repos",
    blurhash: "UPDc%K~UFeEf-o%KtlaLX.%g;ysA=v%2W;R-",
    height: 2104,
    slug: "l-appel-au-repos",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/l-appel-au-repos.jpeg",
    width: 2137,
  },
  {
    alt: "L'endroit qui m'a vue grandir",
    blurhash: "UIE{FZt:NIKh{0[qEOSws#+[+@In5DxDf3nO",
    height: 3750,
    slug: "l-endroit-qui-m-a-vue-grandir",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/l-endroit-qui-m-a-vue-grandir.jpeg",
    width: 3774,
  },
  {
    alt: "La fille à la fougère",
    blurhash: "UBCFkk0f5S}@0x-;nmR6KjwHRjJCrsR-$%Rj",
    height: 3072,
    slug: "la-fille-a-la-fougere",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/la-fille-a-la-fougere.png",
    width: 2222,
  },
  {
    alt: "Logo",
    blurhash: "UlLq|U1k-;Ej5rI;xDs,.T#jnhShNGs-W?I=",
    height: 2000,
    slug: "logo",
    src: "https://ik.imagekit.io/elianacorre/logo.png",
    width: 2000,
  },
  {
    alt: "Mon message au monde",
    blurhash: "UFH1}T?a?^OT.TxaniNdS0Rjofxb={RQNZ%L",
    height: 3888,
    slug: "mon-message-au-monde",
    src: "https://ik.imagekit.io/elianacorre/mon-message-au-monde.jpeg",
    width: 5184,
  },
  {
    alt: "Le bruit de la nuit",
    blurhash: "U46]U|=[4TH=A5L#t,T18wR5$Lx^bvMdrqyY",
    height: 2600,
    slug: "le-bruit-de-la-nuit",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/le-bruit-de-la-nuit.png",
    width: 1955,
  },
  {
    alt: "Mains I",
    blurhash: "UPJQQA$%1%w[~nbYa2nONLOrNbt5MxxaniRj",
    height: 1876,
    slug: "mains-i",
    src: "https://ik.imagekit.io/elianacorre/la-poetique-des-mains/mains-i.png",
    width: 2536,
  },
  {
    alt: "Perdue dans la jungle",
    blurhash: "UaEpA~jDTJWA.AoetmRjX:WCnNt7NfoznhWA",
    height: 4262,
    slug: "perdue-dans-la-jungle",
    src: "https://ik.imagekit.io/elianacorre/animal-totem/perdue-dans-la-jungle.jpeg",
    width: 3076,
  },
  {
    alt: "La volonté",
    blurhash: "UZJjrN}XD%OrJUW;s8a0TJpHWBr?XARjV@of",
    height: 2938,
    slug: "la-volonte",
    src: "https://ik.imagekit.io/elianacorre/animal-totem/la-volonte.jpeg",
    width: 4422,
  },
  {
    alt: "Ma vraie nature",
    blurhash: "UaDm,jyZIonNxZngXUo~TLozxGsloJV?jFax",
    height: 3229,
    slug: "ma-vraie-nature",
    src: "https://ik.imagekit.io/elianacorre/animal-totem/ma-vraie-nature.jpeg",
    width: 4768,
  },
  {
    alt: "Le protecteur",
    blurhash: "U9A]?W$303Ef=Zp0ACRn0~T1}9$$9anN-:Si",
    height: 2613,
    slug: "le-protecteur",
    src: "https://ik.imagekit.io/elianacorre/bestiaire/le-protecteur.png",
    width: 1819,
  },
  {
    alt: "La rêveuse",
    blurhash: "UED,49?aWV+v1NEmbwNGxHt7OWFw}lODEkxG",
    height: 2432,
    slug: "la-reveuse",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/la-reveuse.png",
    width: 1817,
  },
  {
    alt: "Mains II",
    blurhash: "UIHLhx~92vFw15a4wcSh10K1v}X6W-Efrr$j",
    height: 2537,
    slug: "mains-ii",
    src: "https://ik.imagekit.io/elianacorre/la-poetique-des-mains/mains-ii.jpeg",
    width: 1888,
  },
  {
    alt: "Mains III",
    blurhash: "UDCja+}W030{1Hxa#,E3S$E3%L}sAWspaKNb",
    height: 2415,
    slug: "mains-iii",
    src: "https://ik.imagekit.io/elianacorre/la-poetique-des-mains/mains-iii.jpeg",
    width: 1728,
  },
  {
    alt: "Mains IV",
    blurhash: "UBCt%g-=TMOqK*wHW=nOtWO@%LNfO,InMxwK",
    height: 4269,
    slug: "mains-iv",
    src: "https://ik.imagekit.io/elianacorre/la-poetique-des-mains/mains-iv.jpeg",
    width: 2669,
  },
  {
    alt: "Mains V",
    blurhash: "U2GjHkC74g0000~Uye|M00t$.RK$G]D7IWC$",
    height: 4281,
    slug: "mains-v",
    src: "https://ik.imagekit.io/elianacorre/la-poetique-des-mains/mains-v.jpeg",
    width: 2684,
  },
  {
    alt: "Mains VI",
    blurhash: "UAE{b1~3f+EM=:t8DiM{Ou4=.9xY8^Rj.9oI",
    height: 4679,
    slug: "mains-vi",
    src: "https://ik.imagekit.io/elianacorre/la-poetique-des-mains/mains-vi.jpeg",
    width: 3524,
  },
  {
    alt: "Mains VII",
    blurhash: "U8Exw%00EW0Kz;0f-WD%JWE,-V=r}i%30g-o",
    height: 4328,
    slug: "mains-vii",
    src: "https://ik.imagekit.io/elianacorre/la-poetique-des-mains/mains-vii.jpeg",
    width: 3219,
  },
  {
    alt: "Peacock",
    blurhash: "U3698,JCRLoi.YkNRPa+DNv:XWMvDQx_WJNH",
    height: 4096,
    slug: "peacock",
    src: "https://ik.imagekit.io/elianacorre/bestiaire/peacock.jpg",
    width: 3023,
  },
  {
    alt: "Renaissance",
    blurhash: "UKGR#1NGAH?Z_KX5s+.6-:nixZ?Z.PE2s:tQ",
    height: 4790,
    slug: "renaissance",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/renaissance.jpeg",
    width: 3848,
  },
  {
    alt: "Ressentir le monde",
    blurhash: "UOFYuuxZ?[JBr=Rj=rf+KlX7NNs.-Nay%Is,",
    height: 2334,
    slug: "ressentir-le-monde",
    src: "https://ik.imagekit.io/elianacorre/ode-a-la-beaute/ressentir-le-monde.jpeg",
    width: 1724,
  },
  {
    alt: "Serpent vif",
    blurhash: "UfIq@$-m~MxY%esoNdR-%LW;RnRlxtRnV[a#",
    height: 2508,
    slug: "serpent-vif",
    src: "https://ik.imagekit.io/elianacorre/bestiaire/serpent-vif.png",
    width: 1940,
  },
  {
    alt: "Toucan",
    blurhash: "UACGGCa50xNzPlr^nf^30$-5}sE,+EcDS+1b",
    height: 2335,
    slug: "toucan",
    src: "https://ik.imagekit.io/elianacorre/bestiaire/toucan.jpeg",
    width: 1714,
  },
] as const;

export const imageFrom = ({ alt, blurhash, height, src, width }: Images["Entry"]) => ({
  alt,
  background: blurhashToCssGradientString(blurhash),
  height,
  src,
  width,
});

export const readImageBySlug = (slug: Images["Entry"]["slug"]) => {
  const entry = allImages.find((image) => image.slug === slug);
  if (!entry) throw new Error(`Image not found: ${slug}`);
  return imageFrom(entry);
};

export const readImagesBySlugs = (slugs: Images["Entry"]["slug"][]) => allImages.filter(({ slug }) => slugs.includes(slug)).map(imageFrom);

export type Images = { Entity: ReturnType<typeof imageFrom>; Entry: (typeof allImages)[number] };
