/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as OeuvresRouteImport } from './routes/oeuvres'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CarnetsDeVoyageIndexRouteImport } from './routes/carnets-de-voyage/index'
import { Route as ConfidentialiteIndexRouteImport } from './routes/confidentialite/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as MentionsLegalesIndexRouteImport } from './routes/mentions-legales/index'
import { Route as NewsletterConfirmationRouteImport } from './routes/newsletter/confirmation'
import { Route as NewsletterEbookRouteImport } from './routes/newsletter/ebook'
import { Route as OeuvresIndexRouteImport } from './routes/oeuvres/index'
import { Route as OeuvresSlugRouteImport } from './routes/oeuvres/$slug'
import { Route as QuiSuisJeIndexRouteImport } from './routes/qui-suis-je/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OeuvresRoute = OeuvresRouteImport.update({
  id: '/oeuvres',
  path: '/oeuvres',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetsDeVoyageIndexRoute = CarnetsDeVoyageIndexRouteImport.update({
  id: '/carnets-de-voyage/',
  path: '/carnets-de-voyage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteIndexRoute = ConfidentialiteIndexRouteImport.update({
  id: '/confidentialite/',
  path: '/confidentialite/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesIndexRoute = MentionsLegalesIndexRouteImport.update({
  id: '/mentions-legales/',
  path: '/mentions-legales/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmationRoute = NewsletterConfirmationRouteImport.update({
  id: '/newsletter/confirmation',
  path: '/newsletter/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterEbookRoute = NewsletterEbookRouteImport.update({
  id: '/newsletter/ebook',
  path: '/newsletter/ebook',
  getParentRoute: () => rootRouteImport,
} as any)
const OeuvresIndexRoute = OeuvresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OeuvresRoute,
} as any)
const OeuvresSlugRoute = OeuvresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OeuvresRoute,
} as any)
const QuiSuisJeIndexRoute = QuiSuisJeIndexRouteImport.update({
  id: '/qui-suis-je/',
  path: '/qui-suis-je/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/oeuvres': typeof OeuvresRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/newsletter/confirmation': typeof NewsletterConfirmationRoute
  '/newsletter/ebook': typeof NewsletterEbookRoute
  '/oeuvres/$slug': typeof OeuvresSlugRoute
  '/carnets-de-voyage/': typeof CarnetsDeVoyageIndexRoute
  '/confidentialite/': typeof ConfidentialiteIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/mentions-legales/': typeof MentionsLegalesIndexRoute
  '/oeuvres/': typeof OeuvresIndexRoute
  '/qui-suis-je/': typeof QuiSuisJeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/newsletter/confirmation': typeof NewsletterConfirmationRoute
  '/newsletter/ebook': typeof NewsletterEbookRoute
  '/oeuvres/$slug': typeof OeuvresSlugRoute
  '/carnets-de-voyage': typeof CarnetsDeVoyageIndexRoute
  '/confidentialite': typeof ConfidentialiteIndexRoute
  '/contact': typeof ContactIndexRoute
  '/mentions-legales': typeof MentionsLegalesIndexRoute
  '/oeuvres': typeof OeuvresIndexRoute
  '/qui-suis-je': typeof QuiSuisJeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/oeuvres': typeof OeuvresRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/newsletter/confirmation': typeof NewsletterConfirmationRoute
  '/newsletter/ebook': typeof NewsletterEbookRoute
  '/oeuvres/$slug': typeof OeuvresSlugRoute
  '/carnets-de-voyage/': typeof CarnetsDeVoyageIndexRoute
  '/confidentialite/': typeof ConfidentialiteIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/mentions-legales/': typeof MentionsLegalesIndexRoute
  '/oeuvres/': typeof OeuvresIndexRoute
  '/qui-suis-je/': typeof QuiSuisJeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/oeuvres'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/newsletter/confirmation'
    | '/newsletter/ebook'
    | '/oeuvres/$slug'
    | '/carnets-de-voyage/'
    | '/confidentialite/'
    | '/contact/'
    | '/mentions-legales/'
    | '/oeuvres/'
    | '/qui-suis-je/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/newsletter/confirmation'
    | '/newsletter/ebook'
    | '/oeuvres/$slug'
    | '/carnets-de-voyage'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/oeuvres'
    | '/qui-suis-je'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/oeuvres'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/newsletter/confirmation'
    | '/newsletter/ebook'
    | '/oeuvres/$slug'
    | '/carnets-de-voyage/'
    | '/confidentialite/'
    | '/contact/'
    | '/mentions-legales/'
    | '/oeuvres/'
    | '/qui-suis-je/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  OeuvresRoute: typeof OeuvresRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  NewsletterConfirmationRoute: typeof NewsletterConfirmationRoute
  NewsletterEbookRoute: typeof NewsletterEbookRoute
  CarnetsDeVoyageIndexRoute: typeof CarnetsDeVoyageIndexRoute
  ConfidentialiteIndexRoute: typeof ConfidentialiteIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  MentionsLegalesIndexRoute: typeof MentionsLegalesIndexRoute
  QuiSuisJeIndexRoute: typeof QuiSuisJeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oeuvres': {
      id: '/oeuvres'
      path: '/oeuvres'
      fullPath: '/oeuvres'
      preLoaderRoute: typeof OeuvresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnets-de-voyage/': {
      id: '/carnets-de-voyage/'
      path: '/carnets-de-voyage'
      fullPath: '/carnets-de-voyage/'
      preLoaderRoute: typeof CarnetsDeVoyageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite/': {
      id: '/confidentialite/'
      path: '/confidentialite'
      fullPath: '/confidentialite/'
      preLoaderRoute: typeof ConfidentialiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales/': {
      id: '/mentions-legales/'
      path: '/mentions-legales'
      fullPath: '/mentions-legales/'
      preLoaderRoute: typeof MentionsLegalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirmation': {
      id: '/newsletter/confirmation'
      path: '/newsletter/confirmation'
      fullPath: '/newsletter/confirmation'
      preLoaderRoute: typeof NewsletterConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/ebook': {
      id: '/newsletter/ebook'
      path: '/newsletter/ebook'
      fullPath: '/newsletter/ebook'
      preLoaderRoute: typeof NewsletterEbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oeuvres/': {
      id: '/oeuvres/'
      path: '/'
      fullPath: '/oeuvres/'
      preLoaderRoute: typeof OeuvresIndexRouteImport
      parentRoute: typeof OeuvresRoute
    }
    '/oeuvres/$slug': {
      id: '/oeuvres/$slug'
      path: '/$slug'
      fullPath: '/oeuvres/$slug'
      preLoaderRoute: typeof OeuvresSlugRouteImport
      parentRoute: typeof OeuvresRoute
    }
    '/qui-suis-je/': {
      id: '/qui-suis-je/'
      path: '/qui-suis-je'
      fullPath: '/qui-suis-je/'
      preLoaderRoute: typeof QuiSuisJeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OeuvresRouteChildren {
  OeuvresSlugRoute: typeof OeuvresSlugRoute
  OeuvresIndexRoute: typeof OeuvresIndexRoute
}

const OeuvresRouteChildren: OeuvresRouteChildren = {
  OeuvresSlugRoute: OeuvresSlugRoute,
  OeuvresIndexRoute: OeuvresIndexRoute,
}

const OeuvresRouteWithChildren =
  OeuvresRoute._addFileChildren(OeuvresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  OeuvresRoute: OeuvresRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  NewsletterConfirmationRoute: NewsletterConfirmationRoute,
  NewsletterEbookRoute: NewsletterEbookRoute,
  CarnetsDeVoyageIndexRoute: CarnetsDeVoyageIndexRoute,
  ConfidentialiteIndexRoute: ConfidentialiteIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  MentionsLegalesIndexRoute: MentionsLegalesIndexRoute,
  QuiSuisJeIndexRoute: QuiSuisJeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
