/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminEbooksRouteImport } from './routes/admin/ebooks'
import { Route as PublicOeuvresRouteImport } from './routes/_public/oeuvres'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as PublicQuiSuisJeIndexRouteImport } from './routes/_public/qui-suis-je/index'
import { Route as PublicOeuvresIndexRouteImport } from './routes/_public/oeuvres/index'
import { Route as PublicMentionsLegalesIndexRouteImport } from './routes/_public/mentions-legales/index'
import { Route as PublicContactIndexRouteImport } from './routes/_public/contact/index'
import { Route as PublicConfidentialiteIndexRouteImport } from './routes/_public/confidentialite/index'
import { Route as PublicCarnetsDeVoyageIndexRouteImport } from './routes/_public/carnets-de-voyage/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicOeuvresSlugRouteImport } from './routes/_public/oeuvres/$slug'
import { Route as PublicNewsletterEbookRouteImport } from './routes/_public/newsletter/ebook'
import { Route as PublicNewsletterConfirmationRouteImport } from './routes/_public/newsletter/confirmation'

const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminEbooksRoute = AdminEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => AdminRoute,
} as any)
const PublicOeuvresRoute = PublicOeuvresRouteImport.update({
  id: '/oeuvres',
  path: '/oeuvres',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQuiSuisJeIndexRoute = PublicQuiSuisJeIndexRouteImport.update({
  id: '/qui-suis-je/',
  path: '/qui-suis-je/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOeuvresIndexRoute = PublicOeuvresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicOeuvresRoute,
} as any)
const PublicMentionsLegalesIndexRoute =
  PublicMentionsLegalesIndexRouteImport.update({
    id: '/mentions-legales/',
    path: '/mentions-legales/',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicContactIndexRoute = PublicContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConfidentialiteIndexRoute =
  PublicConfidentialiteIndexRouteImport.update({
    id: '/confidentialite/',
    path: '/confidentialite/',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicCarnetsDeVoyageIndexRoute =
  PublicCarnetsDeVoyageIndexRouteImport.update({
    id: '/carnets-de-voyage/',
    path: '/carnets-de-voyage/',
    getParentRoute: () => PublicRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOeuvresSlugRoute = PublicOeuvresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicOeuvresRoute,
} as any)
const PublicNewsletterEbookRoute = PublicNewsletterEbookRouteImport.update({
  id: '/newsletter/ebook',
  path: '/newsletter/ebook',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsletterConfirmationRoute =
  PublicNewsletterConfirmationRouteImport.update({
    id: '/newsletter/confirmation',
    path: '/newsletter/confirmation',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/$': typeof PublicSplatRoute
  '/oeuvres': typeof PublicOeuvresRouteWithChildren
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/': typeof AdminIndexRoute
  '/newsletter/confirmation': typeof PublicNewsletterConfirmationRoute
  '/newsletter/ebook': typeof PublicNewsletterEbookRoute
  '/oeuvres/$slug': typeof PublicOeuvresSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/carnets-de-voyage/': typeof PublicCarnetsDeVoyageIndexRoute
  '/confidentialite/': typeof PublicConfidentialiteIndexRoute
  '/contact/': typeof PublicContactIndexRoute
  '/mentions-legales/': typeof PublicMentionsLegalesIndexRoute
  '/oeuvres/': typeof PublicOeuvresIndexRoute
  '/qui-suis-je/': typeof PublicQuiSuisJeIndexRoute
}
export interface FileRoutesByTo {
  '/connexion': typeof ConnexionRoute
  '/$': typeof PublicSplatRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/newsletter/confirmation': typeof PublicNewsletterConfirmationRoute
  '/newsletter/ebook': typeof PublicNewsletterEbookRoute
  '/oeuvres/$slug': typeof PublicOeuvresSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/carnets-de-voyage': typeof PublicCarnetsDeVoyageIndexRoute
  '/confidentialite': typeof PublicConfidentialiteIndexRoute
  '/contact': typeof PublicContactIndexRoute
  '/mentions-legales': typeof PublicMentionsLegalesIndexRoute
  '/oeuvres': typeof PublicOeuvresIndexRoute
  '/qui-suis-je': typeof PublicQuiSuisJeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/_public/$': typeof PublicSplatRoute
  '/_public/oeuvres': typeof PublicOeuvresRouteWithChildren
  '/admin/ebooks': typeof AdminEbooksRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/newsletter/confirmation': typeof PublicNewsletterConfirmationRoute
  '/_public/newsletter/ebook': typeof PublicNewsletterEbookRoute
  '/_public/oeuvres/$slug': typeof PublicOeuvresSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_public/carnets-de-voyage/': typeof PublicCarnetsDeVoyageIndexRoute
  '/_public/confidentialite/': typeof PublicConfidentialiteIndexRoute
  '/_public/contact/': typeof PublicContactIndexRoute
  '/_public/mentions-legales/': typeof PublicMentionsLegalesIndexRoute
  '/_public/oeuvres/': typeof PublicOeuvresIndexRoute
  '/_public/qui-suis-je/': typeof PublicQuiSuisJeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connexion'
    | '/$'
    | '/oeuvres'
    | '/admin/ebooks'
    | '/admin/'
    | '/newsletter/confirmation'
    | '/newsletter/ebook'
    | '/oeuvres/$slug'
    | '/api/auth/$'
    | '/carnets-de-voyage/'
    | '/confidentialite/'
    | '/contact/'
    | '/mentions-legales/'
    | '/oeuvres/'
    | '/qui-suis-je/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connexion'
    | '/$'
    | '/admin/ebooks'
    | '/'
    | '/admin'
    | '/newsletter/confirmation'
    | '/newsletter/ebook'
    | '/oeuvres/$slug'
    | '/api/auth/$'
    | '/carnets-de-voyage'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/oeuvres'
    | '/qui-suis-je'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/connexion'
    | '/_public/$'
    | '/_public/oeuvres'
    | '/admin/ebooks'
    | '/_public/'
    | '/admin/'
    | '/_public/newsletter/confirmation'
    | '/_public/newsletter/ebook'
    | '/_public/oeuvres/$slug'
    | '/api/auth/$'
    | '/_public/carnets-de-voyage/'
    | '/_public/confidentialite/'
    | '/_public/contact/'
    | '/_public/mentions-legales/'
    | '/_public/oeuvres/'
    | '/_public/qui-suis-je/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/ebooks': {
      id: '/admin/ebooks'
      path: '/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AdminEbooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/oeuvres': {
      id: '/_public/oeuvres'
      path: '/oeuvres'
      fullPath: '/oeuvres'
      preLoaderRoute: typeof PublicOeuvresRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/qui-suis-je/': {
      id: '/_public/qui-suis-je/'
      path: '/qui-suis-je'
      fullPath: '/qui-suis-je/'
      preLoaderRoute: typeof PublicQuiSuisJeIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/oeuvres/': {
      id: '/_public/oeuvres/'
      path: '/'
      fullPath: '/oeuvres/'
      preLoaderRoute: typeof PublicOeuvresIndexRouteImport
      parentRoute: typeof PublicOeuvresRoute
    }
    '/_public/mentions-legales/': {
      id: '/_public/mentions-legales/'
      path: '/mentions-legales'
      fullPath: '/mentions-legales/'
      preLoaderRoute: typeof PublicMentionsLegalesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact/': {
      id: '/_public/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof PublicContactIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/confidentialite/': {
      id: '/_public/confidentialite/'
      path: '/confidentialite'
      fullPath: '/confidentialite/'
      preLoaderRoute: typeof PublicConfidentialiteIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/carnets-de-voyage/': {
      id: '/_public/carnets-de-voyage/'
      path: '/carnets-de-voyage'
      fullPath: '/carnets-de-voyage/'
      preLoaderRoute: typeof PublicCarnetsDeVoyageIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/oeuvres/$slug': {
      id: '/_public/oeuvres/$slug'
      path: '/$slug'
      fullPath: '/oeuvres/$slug'
      preLoaderRoute: typeof PublicOeuvresSlugRouteImport
      parentRoute: typeof PublicOeuvresRoute
    }
    '/_public/newsletter/ebook': {
      id: '/_public/newsletter/ebook'
      path: '/newsletter/ebook'
      fullPath: '/newsletter/ebook'
      preLoaderRoute: typeof PublicNewsletterEbookRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/newsletter/confirmation': {
      id: '/_public/newsletter/confirmation'
      path: '/newsletter/confirmation'
      fullPath: '/newsletter/confirmation'
      preLoaderRoute: typeof PublicNewsletterConfirmationRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicOeuvresRouteChildren {
  PublicOeuvresSlugRoute: typeof PublicOeuvresSlugRoute
  PublicOeuvresIndexRoute: typeof PublicOeuvresIndexRoute
}

const PublicOeuvresRouteChildren: PublicOeuvresRouteChildren = {
  PublicOeuvresSlugRoute: PublicOeuvresSlugRoute,
  PublicOeuvresIndexRoute: PublicOeuvresIndexRoute,
}

const PublicOeuvresRouteWithChildren = PublicOeuvresRoute._addFileChildren(
  PublicOeuvresRouteChildren,
)

interface PublicRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicOeuvresRoute: typeof PublicOeuvresRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
  PublicNewsletterConfirmationRoute: typeof PublicNewsletterConfirmationRoute
  PublicNewsletterEbookRoute: typeof PublicNewsletterEbookRoute
  PublicCarnetsDeVoyageIndexRoute: typeof PublicCarnetsDeVoyageIndexRoute
  PublicConfidentialiteIndexRoute: typeof PublicConfidentialiteIndexRoute
  PublicContactIndexRoute: typeof PublicContactIndexRoute
  PublicMentionsLegalesIndexRoute: typeof PublicMentionsLegalesIndexRoute
  PublicQuiSuisJeIndexRoute: typeof PublicQuiSuisJeIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicOeuvresRoute: PublicOeuvresRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
  PublicNewsletterConfirmationRoute: PublicNewsletterConfirmationRoute,
  PublicNewsletterEbookRoute: PublicNewsletterEbookRoute,
  PublicCarnetsDeVoyageIndexRoute: PublicCarnetsDeVoyageIndexRoute,
  PublicConfidentialiteIndexRoute: PublicConfidentialiteIndexRoute,
  PublicContactIndexRoute: PublicContactIndexRoute,
  PublicMentionsLegalesIndexRoute: PublicMentionsLegalesIndexRoute,
  PublicQuiSuisJeIndexRoute: PublicQuiSuisJeIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminEbooksRoute: typeof AdminEbooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEbooksRoute: AdminEbooksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
