/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuiSuisJeRouteImport } from './routes/qui-suis-je'
import { Route as OeuvresRouteImport } from './routes/oeuvres'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as CarnetsDeVoyageRouteImport } from './routes/carnets-de-voyage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OeuvresIndexRouteImport } from './routes/oeuvres.index'
import { Route as OeuvresSlugRouteImport } from './routes/oeuvres.$slug'

const QuiSuisJeRoute = QuiSuisJeRouteImport.update({
  id: '/qui-suis-je',
  path: '/qui-suis-je',
  getParentRoute: () => rootRouteImport,
} as any)
const OeuvresRoute = OeuvresRouteImport.update({
  id: '/oeuvres',
  path: '/oeuvres',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetsDeVoyageRoute = CarnetsDeVoyageRouteImport.update({
  id: '/carnets-de-voyage',
  path: '/carnets-de-voyage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OeuvresIndexRoute = OeuvresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OeuvresRoute,
} as any)
const OeuvresSlugRoute = OeuvresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OeuvresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carnets-de-voyage': typeof CarnetsDeVoyageRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/oeuvres': typeof OeuvresRouteWithChildren
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/oeuvres/$slug': typeof OeuvresSlugRoute
  '/oeuvres/': typeof OeuvresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carnets-de-voyage': typeof CarnetsDeVoyageRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/oeuvres/$slug': typeof OeuvresSlugRoute
  '/oeuvres': typeof OeuvresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carnets-de-voyage': typeof CarnetsDeVoyageRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/oeuvres': typeof OeuvresRouteWithChildren
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/oeuvres/$slug': typeof OeuvresSlugRoute
  '/oeuvres/': typeof OeuvresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carnets-de-voyage'
    | '/mentions-legales'
    | '/oeuvres'
    | '/qui-suis-je'
    | '/oeuvres/$slug'
    | '/oeuvres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carnets-de-voyage'
    | '/mentions-legales'
    | '/qui-suis-je'
    | '/oeuvres/$slug'
    | '/oeuvres'
  id:
    | '__root__'
    | '/'
    | '/carnets-de-voyage'
    | '/mentions-legales'
    | '/oeuvres'
    | '/qui-suis-je'
    | '/oeuvres/$slug'
    | '/oeuvres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarnetsDeVoyageRoute: typeof CarnetsDeVoyageRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OeuvresRoute: typeof OeuvresRouteWithChildren
  QuiSuisJeRoute: typeof QuiSuisJeRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/qui-suis-je': {
      id: '/qui-suis-je'
      path: '/qui-suis-je'
      fullPath: '/qui-suis-je'
      preLoaderRoute: typeof QuiSuisJeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oeuvres': {
      id: '/oeuvres'
      path: '/oeuvres'
      fullPath: '/oeuvres'
      preLoaderRoute: typeof OeuvresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnets-de-voyage': {
      id: '/carnets-de-voyage'
      path: '/carnets-de-voyage'
      fullPath: '/carnets-de-voyage'
      preLoaderRoute: typeof CarnetsDeVoyageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oeuvres/': {
      id: '/oeuvres/'
      path: '/'
      fullPath: '/oeuvres/'
      preLoaderRoute: typeof OeuvresIndexRouteImport
      parentRoute: typeof OeuvresRoute
    }
    '/oeuvres/$slug': {
      id: '/oeuvres/$slug'
      path: '/$slug'
      fullPath: '/oeuvres/$slug'
      preLoaderRoute: typeof OeuvresSlugRouteImport
      parentRoute: typeof OeuvresRoute
    }
  }
}

interface OeuvresRouteChildren {
  OeuvresSlugRoute: typeof OeuvresSlugRoute
  OeuvresIndexRoute: typeof OeuvresIndexRoute
}

const OeuvresRouteChildren: OeuvresRouteChildren = {
  OeuvresSlugRoute: OeuvresSlugRoute,
  OeuvresIndexRoute: OeuvresIndexRoute,
}

const OeuvresRouteWithChildren =
  OeuvresRoute._addFileChildren(OeuvresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarnetsDeVoyageRoute: CarnetsDeVoyageRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OeuvresRoute: OeuvresRouteWithChildren,
  QuiSuisJeRoute: QuiSuisJeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
