export const HTTP_HEADER = {
  allow: "Allow",
  authorization: "Authorization",
  cacheControl: "Cache-Control",
  contentSecurityPolicy: "Content-Security-Policy",
  contentSecurityPolicyReportOnly: "Content-Security-Policy-Report-Only",
  contentType: "Content-Type",
  cookie: "Cookie",
  permissionsPolicy: "Permissions-Policy",
  referrerPolicy: "Referrer-Policy",
  setCookie: "Set-Cookie",
  strictTransportSecurity: "Strict-Transport-Security",
  wwwAuthenticate: "WWW-Authenticate",
  xContentTypeOptions: "X-Content-Type-Options",
  xFrameOptions: "X-Frame-Options",
} as const;
